<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
name: CLA Corporate Console
machine_name: ccc
=======
name: Project Management Console
machine_name: pmc
>>>>>>> c5f1638d55afe98cb0fba6aae1d02963daea833e
=======
name: CLA Console
machine_name: cla-console
>>>>>>> 6e949e3c936f47f3710f0e3fe3859fed5818fa3b
stack: nodejs
modes:
  - default
  - dev
dependencies:
<<<<<<< HEAD
<<<<<<< HEAD
=======
  - cinco
>>>>>>> c5f1638d55afe98cb0fba6aae1d02963daea833e
=======
>>>>>>> 6e949e3c936f47f3710f0e3fe3859fed5818fa3b
  - cla
=======
name: CLA System
machine_name: cla
stack: python
dependencies:
- cinco
>>>>>>> ddcd55ee69621b91435657356d5de16da46cc364
files:
