version: 2.1

jobs:
  # Builds
  buildBackend:
    docker:
      - image: circleci/python:3.6-node
    steps:
      - checkout
      - run:
          name: Install Top Level Dependencies
          command: yarn install
      - run:
          name: Install awscli
          command: sudo apt-get install -y awscli
      - run:
          name: make setup
          command: cd cla-backend && make setup_circle
      - run:
          name: List working dir
          command: ls
      - run:
          name: Copy Workspace To Avoid Conflicts
          command: mv ~/project ~/backend
      - persist_to_workspace:
          root: ~/
          paths:
            - backend/package.json
            - backend/cla-backend
            - backend/scripts
            - backend/project-vars.yml

  buildGoBackend:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/communitybridge/easy-cla/
    steps:
      - checkout
      - run: go get -u github.com/go-swagger/go-swagger/cmd/swagger
      - run: cd cla-backend-go; make swagger; make build_aws_lambda
      - run: mv cla-backend-go ~/cla-backend-go
      - persist_to_workspace:
          root: ~/
          paths:
            - cla-backend-go/backend_aws_lambda

  buildUIProject: &buildUIAnchor
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Install Top Level Dependencies
          command: yarn install
      - run:
          name: Install Dependencies
          command: cd $PROJECT_DIR && make setup
      - run:
          name: Copy Workspace To Avoid Conflicts
          command: mv /home/circleci/project "/home/circleci/$PROJECT_DIR-workspace"
      - persist_to_workspace:
          root: ~/
          paths:
            - ./*

  buildProjectManagementConsole:
    <<: *buildUIAnchor
    environment:
      PROJECT_DIR: cla-frontend-project-console

  buildCorporateManagementConsole:
    <<: *buildUIAnchor
    environment:
      PROJECT_DIR: cla-frontend-corporate-console

  buildContributorConsole:
    <<: *buildUIAnchor
    environment:
      PROJECT_DIR: cla-frontend-contributor-console

workflows:
  version: 2.1
  build:
    jobs:
      - buildBackend:
          filters:
            tags:
              only: /.*/
      - buildGoBackend:
          requires:
            - buildBackend
          filters:
            tags:
              only: /.*/
      - buildProjectManagementConsole:
          requires:
            - buildBackend
            - buildGoBackend
          filters:
            tags:
              only: /.*/
      - buildCorporateManagementConsole:
          requires:
            - buildProjectManagementConsole
          filters:
            tags:
              only: /.*/
      - buildContributorConsole:
          requires:
            - buildCorporateManagementConsole
          filters:
            tags:
              only: /.*/
