# List of all the containers that needs to be spun up.
# The workspace container will be added and configured automatically.
# The Syntax for each container should mimic the docker-compose format.
containers:
  redis:
    image: '433610389961.dkr.ecr.us-west-2.amazonaws.com/redis:latest'
    volumes: ['./logs/redis:/var/log/redis']
  workspace:
    ports: ['%:8081']

# Environment Variables to be injected in the container.
environment:
  workspace:
    console_integration_user: 'cinco'
    console_integration_password: 'cinco'
    encryption_sauce: 'WqNGjk@%ym7eRsXGAZYskF'
    redis_host: 'redis'
    redis_port: '6379'

sequences:

  jenkins:
    Doing Nothing: 'echo \"Skipping Installation Procedures\"'

  install:
    Installing Dependencies: "cd /srv/app/src && npm install --quiet"

  start:
    _detach: True
    Launching Console: "cd /srv/app/src && npm run develop"
