---
# Copyright The Linux Foundation and each contributor to CommunityBridge.
# SPDX-License-Identifier: MIT

name: Build and Test Pull Request
on:
  pull_request:
    branches:
      - main

env:
  STAGE: dev

jobs:
  build-pr:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'
      - name: Go Version
        run: go version
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pip'
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Configure Git to clone private Github repos
        run: git config --global url."https://${TOKEN_USER}:${TOKEN}@github.com".insteadOf "https://github.com"
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TOKEN_USER: ${{ secrets.PERSONAL_ACCESS_TOKEN_USER }}

      - name: Add OS Tools
        run: sudo apt update && sudo apt-get install file -y

      - name: Python Setup
        working-directory: cla-backend
        run: |
          pip install -r requirements.txt

      - name: Python Lint
        working-directory: cla-backend
        run: |
          pylint cla/*.py || true

      - name: Python Test
        working-directory: cla-backend
        run: |
          pytest "cla/tests" -p no:warnings
        env:
          PLATFORM_GATEWAY_URL: https://api-gw.dev.platform.linuxfoundation.org
          AUTH0_PLATFORM_URL: https://linuxfoundation-dev.auth0.com/oauth/token
          AUTH0_PLATFORM_CLIENT_ID: ${{ secrets.AUTH0_PLATFORM_CLIENT_ID }}
          AUTH0_PLATFORM_CLIENT_SECRET: ${{ secrets.AUTH0_PLATFORM_CLIENT_SECRET }}
          AUTH0_PLATFORM_AUDIENCE: https://api-gw.dev.platform.linuxfoundation.org/

      - name: Go Setup
        working-directory: cla-backend-go
        run: |
          make clean setup

      - name: Go Dependencies
        working-directory: cla-backend-go
        run: make deps

      - name: Go Swagger Generate
        working-directory: cla-backend-go
        run: |
          make swagger

      - name: Go Build
        working-directory: cla-backend-go
        run: |
          make build-lambdas-linux build-functional-tests-linux

      - name: Go Test
        working-directory: cla-backend-go
        run: |
          make test

      - name: Go Lint
        working-directory: cla-backend-go
        run: make lint
