---
# Copyright The Linux Foundation and each contributor to CommunityBridge.
# SPDX-License-Identifier: MIT

name: Build and Test Pull Request
on:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_PROFILE: lf-cla
  STAGE: dev

jobs:
  build-pr:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.5'
      - name: Go Version
        run: go version
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 900
      - name: Setup AWS Profile
        run: |
          echo "Installing Profile '${AWS_PROFILE}'..."
          mkdir -p ~/.aws

          touch ~/.aws/config
          if ! grep -q AWS_PROFILE ~/.aws/config; then
            printf "[profile ${AWS_PROFILE}]\nregion=${AWS_REGION}\noutput=json" > ~/.aws/config
            echo "Added ${AWS_PROFILE} profile to ~/.aws/config"
          else
            echo "Skipped adding ${AWS_PROFILE} to ~/.aws/config - already there"
          fi

          touch ~/.aws/credentials
          if ! grep -q AWS_PROFILE ~/.aws/credentials; then
            printf "[${AWS_PROFILE}]\naws_access_key_id=${{ secrets.AWS_ACCESS_KEY }}\naws_secret_access_key=${{ secrets.AWS_SECRET_KEY }}" > ~/.aws/credentials
            echo "Added ${AWS_PROFILE} profile to ~/.aws/credentials"
          else
            echo "Skipped adding ${AWS_PROFILE} to ~/.aws/credentials - already there"
          fi

          if ! grep -q AWS_PROFILE ${HOME}/.bashrc; then
            echo "export AWS_PROFILE=${AWS_PROFILE}" >> ${HOME}/.bashrc
            echo "Added ${AWS_PROFILE} profile to ${HOME}/.bashrc"
          else
            echo "Skipped adding ${AWS_PROFILE} to ${HOME}/.bashrc - already there"
          fi
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Configure Git to clone private Github repos
        run: git config --global url."https://${TOKEN_USER}:${TOKEN}@github.com".insteadOf "https://github.com"
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB}}
          TOKEN_USER: ${{ secrets.PERSONAL_ACCESS_TOKEN_USER_GITHUB}}

      - name: Add OS Tools
        run: sudo apt update && sudo apt-get install file -y

      - name: Python Setup
        working-directory: cla-backend
        run: |
          pip install -r requirements.txt

      - name: Python Lint
        working-directory: cla-backend
        run: |
          pylint cla/*.py || true

      - name: Python Test
        working-directory: cla-backend
        run: |
          pytest "cla/tests" -p no:warnings
        env:
          PLATFORM_GATEWAY_URL: https://api-gw.dev.platform.linuxfoundation.org
          AUTH0_PLATFORM_URL: https://linuxfoundation-dev.auth0.com/oauth/token
          AUTH0_PLATFORM_CLIENT_ID: ${{ secrets.AUTH0_PLATFORM_CLIENT_ID }}
          AUTH0_PLATFORM_CLIENT_SECRET: ${{ secrets.AUTH0_PLATFORM_CLIENT_SECRET }}
          AUTH0_PLATFORM_AUDIENCE: https://api-gw.dev.platform.linuxfoundation.org/

      - name: Go Setup
        working-directory: cla-backend-go
        run: |
          make clean setup

      - name: Go Dependencies
        working-directory: cla-backend-go
        run: make deps

      - name: Go Swagger Generate
        working-directory: cla-backend-go
        run: |
          make swagger

      - name: Go Build
        working-directory: cla-backend-go
        run: |
          make build-lambdas-linux build-functional-tests-linux

      - name: Go Test
        working-directory: cla-backend-go
        run: |
          make test

      - name: Go Lint
        working-directory: cla-backend-go
        run: make lint
